service: s3-presign
frameworkVersion: '2'
useDotenv: true

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev

functions:
  s3_presign:
    handler: handler.s3_presign
    events:
      - http:
          method: get
          path: /api/s3_presign_url
          request:
            template:
                application/json: >
                    {
                        "bucket": "$input.params('bucket')"
                        "acl": "$input.params('acl')"
                        "content_type": "$input.params('content_type')"
                    }
